# Generated by Django 5.0.4 on 2024-05-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_blog_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
